spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 500
        response-timeout: 1s
      routes:
        - id: amusing-order-server
          uri: lb:http://amusing-order-server
          predicates:
            - Path=/order/outward/**
        - id: amusing-product-server
          uri: lb:http://amusing-product-server
          predicates:
            - Path=/product/outward/**
        - id: amusing-search-server
          uri: lb:http://amusing-search-server
          predicates:
            - Path=/search/outward/**
        - id: amusing-user-server
          uri: lb:http://amusing-user-server
          predicates:
            - Path=/user/outward/**